version: '2'
services:

  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"

  fluentd:
    build: fluentd/
    ports:
      - "9292:9292"
      - "9880:9880"
      - "24224:24224"
      - "24284:24284"
      - "5170:5170"
    volumes:
      - ./fluentd/:/fluentd/etc/
    depends_on:
      - elasticsearch

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
