stack: jussir/loki
description: |
  Lokkaushomma
version: '2.6'
services:
  elasticsearch:
    affinity:
      - label==loki-kone
    image: registry.plat2.leonidasoy.fi/loki-elasticsearch
    ports: []
    stateful: true
    environment:
      - KONTENA_LB_MODE=tcp
      - KONTENA_LB_EXTERNAL_PORT=9200
      - KONTENA_LB_INTERNAL_PORT=9200

  elasticsearch-exporter:
    affinity:
      - label==loki-kone
    image: registry.plat2.leonidasoy.fi/loki-elasticsearch-exporter
    links:
      - elasticsearch
    command: bin/elasticsearch_exporter --es.uri=elasticsearch:8500

  fluentd:
    affinity:
      - label==loki-kone
    image: registry.plat2.leonidasoy.fi/loki-fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes: []
    depends_on:
      - elasticsearch

  kibana:
    affinity:
      - label==loki-kone
    image: registry.plat2.leonidasoy.fi/loki-kibana
    ports: []
    volumes: []
    environment:
      KONTENA_LB_MODE: http
      KONTENA_LB_BALANCE: roundrobin
      KONTENA_LB_INTERNAL_PORT: 5601
      KONTENA_LB_VIRTUAL_HOSTS: loki.leonidasoy.fi
      KONTENA_LB_CUSTOM_SETTINGS: |
        redirect scheme https if !{ ssl_fc }
        http-response set-header Strict-Transport-Security max-age=16000000;\ includeSubDomains;\ preload;
    links:
      - platform/lb1
    secrets:
      - name: KONTENA_LB_BASIC_AUTH_SECRETS
        secret: KIBANA_BASIC_AUTH
        type: env
    depends_on:
      - elasticsearch
