stack: jussir/loki
description: |
  Lokkaushomma
version: '2.5'
services:
  elasticsearch:
    affinity:
      - label==loki-kone
    image: image-registry.leonidasoy.fi/loki-elasticsearch:v4
    ports: []
    volumes: []
    stateful: true
    environment:
      - KONTENA_LB_MODE=tcp
      - KONTENA_LB_EXTERNAL_PORT=9200
      - KONTENA_LB_INTERNAL_PORT=9200
    extends:
      file: docker-compose.yml
      service: elasticsearch

  fluentd:
    affinity:
      - label==loki-kone
    image: image-registry.leonidasoy.fi/loki-fluentd:v4
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes: []
    extends:
      file: docker-compose.yml
      service: fluentd
    depends_on:
      - elasticsearch

  kibana:
    affinity:
      - label==loki-kone
    image: image-registry.leonidasoy.fi/loki-kibana:v4
    ports: []
    volumes: []
    extends:
      file: docker-compose.yml
      service: kibana
    environment:
      - KONTENA_LB_MODE=http
      - KONTENA_LB_BALANCE=roundrobin
      - KONTENA_LB_INTERNAL_PORT=5601
      - KONTENA_LB_VIRTUAL_HOSTS=loki.leonidasoy.fi
      - "KONTENA_LB_CUSTOM_SETTINGS=redirect scheme https if !{ ssl_fc }"
    links:
      - platform/lb1
    secrets:
      - name: KONTENA_LB_BASIC_AUTH_SECRETS
        secret: BASIC_AUTH_FOR_KIBANA1
        type: env
    depends_on:
      - elasticsearch
